### ISSUE TITLE
key sequence i j starts with non-prefix key i

### ISSUE THREAD

**Issue by OrcsBR** [bastibe/org-journal#268] opened 2020-06-27 17:36 UTC
**Describe the bug**
When trying to open emacs calendar dependent functions in org-mode, with shortcut `C-c .` for instance , calendar doesnt comes up front, and user receives the warning on the mini-buffer: "key sequence i j starts with non-prefix key i"

**To Reproduce**
Try to use calendar based functions in org-mode.

**Expected behavior**
Calendar should get properly displayed.

**Desktop (please complete the following information):**
 - OS: pop! os 20.04
 - Emacs Version 26.3
 - Org 20200622 (org repository)

I really don't have much special in my org config, pretty much stock packages installed and the fact that I run the "bleeding edge" org from their repository other than stock.

I also searched for `i j`  in my init.el file, nothing was found.

I fixed this for the time being by changing the `i j` key sequence inside org-journal.el to `f j`, recompiling it and locking the version with package-load-list variable.

Being an emacs noob, i believe there must be another way to fix that by managing prefix keybinding, but I chose the lazy path for now.

**Comment by cslux** [comment] 2020-06-27 18:02
I can't reproduce it. Can you share your org-journal setup please. Also try it with just org-journal loaded  `emacs -Q -l init.el`. Also try it with org-plus-contrib from MELPA. Or the version which comes with emacs.

**Comment by OrcsBR** [comment] 2020-06-29 07:14
```
(define-key org-mode-map (kbd "C-c j") 'org-journal-new-entry)

(use-package org-journal
  :bind
  ("C-c f j" . org-journal-new-entry) 
  :custom
  (org-journal-date-prefix "#+title: ")
  (org-journal-file-format "%Y-%m-%d.org")
  (org-journal-dir "~/Dropbox/OrgRoam/Journal/")
  (org-journal-date-format "%A, %d %B %Y"))

(defun org-journal-find-location ()
  ;; Open today's journal, but specify a non-nil prefix argument in order to
  ;; inhibit inserting the heading; org-capture will insert the heading.
  (org-journal-new-entry t)
  ;; Position point on the journal's top-level heading so that org-capture
  ;; will add the new entry as a child entry.
  (goto-char (point-min)))
```
I can confirm this only happened with version 20200622 (now 20200629) from the org repository. Using 9.3.6 from GNU ELPA did not trigger the issue, at least for me.

**Comment by cslux** [comment] 2020-06-29 11:04
Thanks for verifying it. I'll try to pin down the issue with org-HEAD.

**Comment by cslux** [comment] 2020-06-29 16:18
@OrcsBR I was not able to reproduce it with version release_9.3.7-660-g73e367. Must be some misconfiguration of Emacs on your side. I would stick with org-plus-contrib! 

If you find out the cause and it comes out that org-journal has indeed a bug, feel free to reopen this issue.

**Comment by cslux** [comment] 2020-07-01 15:13
@OrcsBR Should be fixed now!

**Closed** 2020-07-01 15:12 UTC
Labels: bug

**Comment by OrcsBR** [comment] 2020-07-01 20:14
thanks, it works for me!
