### ISSUE TITLE
spacemacs freezes when editing todays journal

### ISSUE THREAD

**Issue by postelrich** [bastibe/org-journal#206] opened 2020-03-08 04:53 UTC
Whether I try to make an entry through `org-journal-new-entry` or with `calendar`, spacemacs freezes up and I have to close the window. I can make entries for any other day without issue.

```
 (org :variables
          org-enable-org-journal-support t
          org-journal-dir "/mnt/c/Users/poste/Dropbox/journal/"
          org-journal-file-format "%Y-%m-%d.org"
          org-journal-date-prefix "#+TITLE: "
          org-journal-date-format "%A, %B %d %Y")
```
org-journal-20200305.1909
spacemacs 0.200.13@26.3`

**Comment by cslux** [comment] 2020-03-08 16:56
Hey!

Can you quite the current loop using C-g? If yes, please call
`toggle-debug-on-quit` and press it.

**Comment by postelrich** [comment] 2020-03-09 03:18
Yes, I was able to get back control with C-g. I ran `toggle-debug-on-quit`, what does that do?

**Comment by cslux** [comment] 2020-03-09 07:47
If you call `toggle-debug-on-quit` and you call the function which hangs in a loop and press `C-g`, the debugger will be opened. You will see the current stacktrace in the debugger, please post the stacktrace here.

**Comment by postelrich** [comment] 2020-03-10 03:08
```
Debugger entered--Lisp error: (quit)
  org-scan-tags(org-decrypt-entry (lambda (todo tags-list level) (progn (setq org-cached-props nil) (or (and (member "crypt" tags-list))))) nil)
  org-decrypt-entries()
  org-journal-decrypt()
  org-journal-finalize-view()
  org-journal-open-entry("No previous journal entry before this one" t no-select)
  org-journal-open-previous-entry(no-select)
  org-journal-carryover()
  org-journal-new-entry(nil)
  funcall-interactively(org-journal-new-entry nil)
  call-interactively(org-journal-new-entry nil nil)
  command-execute(org-journal-new-entry)
```

**Comment by postelrich** [comment] 2020-03-10 03:09
This is on ubuntu wsl on win10 btw.

**Comment by cslux** [comment] 2020-03-10 06:49
Hmm, I cant really see anything obvious strange in the backtrace, must be some problem occurring only in Windows/Ubuntu combination. I guess it has something to do with crypt, but that is actually not a org-journal thing. 

Please can you try the following: 

Change the defun
``` emacs-lisp
(defun org-journal-decrypt ()
  (when (fboundp 'org-decrypt-entries)
    (let ((buffer-read-only nil))
      (org-decrypt-entries))))
```
---->
``` emacs-lisp
(defun org-journal-decrypt ()
  (when (fboundp 'org-decrypt-entries)
    (let ((buffer-read-only nil))
      ;;(org-decrypt-entries)
)))
```
And re-evaluate it, and try if that fixes your problem?

**Comment by bastibe** [comment] 2020-03-10 07:33
There can be funky issues at the interface between Windows and Linux. Are you running this entirely inside the WSL (Linux Emacs on the Linux file system)?

**Comment by postelrich** [comment] 2020-03-11 03:25
With commenting out that line it still freezes, looks it hangs on the regex. Maybe its searching some higher level directory it shouldnt be.

```
Debugger entered--Lisp error: (quit)
  re-search-forward("^\\*+  *\\(\\<\\(DONE\\|TODO\\)\\>\\)? *\\(.*?\\)\\([ \011]:\\(?:[[:alnum:]_@#%]+:\\)+\\)?[ \011]*$" nil t)
  org-scan-tags(org-decrypt-entry (lambda (todo tags-list level) (progn (setq org-cached-props nil) (or (and (member "crypt" tags-list))))) nil)
  org-decrypt-entries()
  org-journal-decrypt()
  org-journal-finalize-view()
  org-journal-open-entry("No previous journal entry before this one" t no-select)
  org-journal-open-previous-entry(no-select)
  org-journal-carryover()
  org-journal-new-entry(nil)
  funcall-interactively(org-journal-new-entry nil)
  call-interactively(org-journal-new-entry nil nil)
  command-execute(org-journal-new-entry)
```

**Comment by cslux** [comment] 2020-03-11 07:00
I'm afraid, but I think you are at the wrong spot to search for help for this kind of issue.

> With commenting out that line it still freezes, looks it hangs on the regex. Maybe its searching some higher level directory it shouldnt be.

That's impossible. If you did, than `org-journal-decrypt` shouldn't have been called. Did you re-evaluate the function?

**Comment by cslux** [comment] 2020-03-11 07:12
The function `org-journal-decrypt` will now only proceed if `org-journal-enable-encryption` is `t`. If you install that version org-decrypt-entries shouldn't be called.

**Comment by cslux** [comment] 2020-03-20 10:29
Closing, as the root cause is somewhere else!

**Closed by cslux** 2020-03-20 10:29 UTC
