### ISSUE TITLE
Search errors: Search failed: " *:CREATED: *[0-9]\\{8\\}"

### ISSUE THREAD

**Issue by jackbaty** [bastibe/org-journal#160] opened 2019-05-16 18:18 UTC
When searching (`org-search-search`) the following happens:

- `M-x org-journal-search`
- I enter the search term
- I enter a date range: e.g. "-1y" until today (default)
- I hit enter to start search

The search can take up to 10 seconds (yet there are only 250 files in my journal directory).

Then this:

```
Buffer 20190501 modified; kill anyway? (y or n) n
org-journal-search-print-results: Search failed: " *:CREATED: *[0-9]\\{8\\}"
```
The search was initiated from this month's journal file: 20190501. I'm not sure why the buffer wants to be automatically killed after searching, perhaps that's a separate issue.

Here's my config. Notice I'm using "monthly" files, which I suspect is part of the problem, but I believe I've seen the error using daily files as well.

```
(use-package org-journal
 :ensure t
 :defer t
 :init
 (setq org-journal-dir "~/org/journal/"
       org-journal-file-type 'monthly
       ;;org-journal-file-format "%Y-%m-%d.org"
       org-journal-find-file #'find-file
       org-journal-time-prefix "** "
       org-journal-time-format ""
       org-journal-enable-agenda-integration t
       org-journal-enable-encryption nil
       org-journal-date-format "%A, %B %d %Y")
:bind  (("C-c j" . org-journal-new-entry)))
```

**Comment by cslux** [comment] 2019-05-17 06:19
> The search can take up to 10 seconds (yet there are only 250 files in my journal directory).

Some profiling results would be nice. M-x profiler-start.

> `Buffer 20190501 modified; kill anyway? (y or n) n`

That shouldn't happen, any already open file shouldn't be killed, especially not modified ones.

> org-journal-search-print-results: Search failed: " *:CREATED: *[0-9]\\{8\\}"

I couldn't reproduce this until now. But It very likely happens when undoing a `org-journal-new-entry`, and doing a search afterwards.

I'll look into that issue

**Comment by cslux** [comment] 2019-05-17 14:44
@jackbaty Should be fixed!

**Closed** 2019-05-17 14:44 UTC
Labels: bug

**Comment by jackbaty** [comment] 2019-05-18 11:32
Ah, that's much better, thank you! Search is nearly instant again, although I did notice search only seems to include what would be monthly files (e.g. 20190401) and does not search daily files (e.g. 20190406). This is probably correct, but since I've only recently changed my journal from daily to monthly files it means I'll have to consolidate the old daily files into one for each month.

Thanks for the fix!

**Comment by cslux** [comment] 2019-05-19 12:19
> Search is nearly instant again, although I did notice search only seems to include what would be monthly files (e.g. 20190401) and does not search daily files (e.g. 20190406). This is probably correct, but since I've only recently changed my journal from daily to monthly files it means I'll have to consolidate the old daily files into one for each month.

Unfortunately we don't have any conversation function included at the moment. For 'weekly, 'monthly and 'yearly journal files you need to set a CREATED property.

**Comment by jackbaty** [comment] 2019-05-19 12:30
Thanks. It shouldn't be too difficult to combine them myself. Thanks for the tip about the CREATED property.

**Comment by cslux** [comment] 2019-05-19 13:47
Hmm, this is a good start point. It doesn't cover each and every corner case but is a good start point.
If you haven't changed `org-journal-file-format` it should work out of the box, no guaranty :-P (That doesn't mean I haven't tested it)
I have also assumed that the `org-journal-date-prefix` is unchanged.
It will create a temporary buffer "* org-journal-convert *" containing all daily entries with the correct org property. Your daily journal files will not be modified.

``` emacs-lisp
(defun org-journal-convert (daily-journal-dir)
  "Convert org-journal daily entry to correct weekly/monthly/yearly journal."
  (interactive "f")
  (let ((files (directory-files daily-journal-dir t "[0-9]\\{8\\}\\(\.gpg\\)?"))
        (buf (generate-new-buffer "* org-journal-convert *")))
    (while files
      (let* ((file (car files))
             (file-nondirectory (file-name-nondirectory file))
             (date (progn
                     (string-match "\\([0-9]\\{8\\}\\)\\(\.gpg\\)?" file-nondirectory)
                     (match-string 1 file-nondirectory))))
        (with-temp-buffer
          (insert-file-contents file)
          (goto-char (point-min))
          (re-search-forward "^\*")
          (goto-char (point-at-bol))
          (org-journal-decrypt)
          (org-set-property "CREATED" date)
          (org-copy-subtree)
          (with-current-buffer buf
            (goto-char (point-max))
            (org-yank))))
      (setq files (cdr files)))))
```

**Comment by jackbaty** [comment] 2019-05-19 14:31
Thanks so much. I'll give this a try as soon as I can.
