### ISSUE TITLE
helm-M-x-execute-command: Invalid version syntax: ‘’ (must start with a number) when org-roam is installed

### ISSUE THREAD

**Issue by madjestic** [bastibe/org-journal#324] opened 2021-01-21 23:31 UTC
**Describe the bug**
Whenever I install org-roam and try to activate org-journal-mode with `M-x org-journal-mode` I get the following error:
```
helm-M-x-execute-command: Invalid version syntax: ‘’ (must start with a number) when org-roam is installed
```
It does not matter if helm is installed, I tried using bare-minimum config with nothing but `package` (to access melpa) and `org-roam` and `org-journal` installed and the result is similar.  One or another works, but not together.

**To Reproduce**
Install `org-roam` and `org-journal-mode` together and try to activate `org-journal-mode` with `M-x org-journal-mode`

**Result**
The error `Invalid version syntax: ‘’ (must start with a number)` should appear in the status bar and journal mode fails to start.

**Expected behavior**
Journal mode should work as expected without throwing an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/3270083/105425085-f99abb00-5c48-11eb-9121-80179aeca0ff.png)

**Desktop (please complete the following information):**
 - OS: Linux-5.4.80-gentoo-r1
 - Emacs Version [26.3-r3]

**Your Emacs Configuration**
```
(use-package org-journal
  :after org
  :bind
  ("C-c n n" . org-journal-new-entry)
  :custom
  (org-journal-date-prefix "#+title: ")
  (org-journal-file-format "%Y-%m-%d.org")
  (org-journal-dir "/home/madjestic/org-roam/")
  (org-journal-date-format "%A, %d %B %Y"))

(use-package org-roam
      :hook
      (after-init . org-roam-mode)
      :custom
      (org-roam-directory "/home/madjestic/org-roam/")
      :bind (:map org-roam-mode-map
              (("C-c n l" . org-roam) ;; toggle links window
               ("C-c n f" . org-roam-find-file)
               ("C-c n j" . org-roam-jump-to-index)
               ("C-c n b" . org-roam-switch-to-buffer)
               ("C-c n g" . org-roam-graph))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))))
```

Cheers,
Vlad

**Comment by cslux** [comment] 2021-01-22 07:37
Duplicate of #317.  Try it with the org or org-plus-contrib package from the orgmode archive repo. It should work!
https://orgmode.org/elpa.html The builtin in version of org shouldn't lead to this error to. 

Did you install org from the gnu elpa repo?

**Closed by cslux** 2021-01-22 07:37 UTC
Labels: duplicate

**Comment by madjestic** [comment] 2021-01-22 09:06
I installed org-roam from melpa.

**Comment by cslux** [comment] 2021-01-22 10:00
This should work as a workaround too.

``` emacs-lisp
(eval-after-load "org" (setq org-version "9.4.4")) ;; or whatever org version you have installed
```
