### ISSUE TITLE
Adding journal files to agenda search

### ISSUE THREAD

**Issue by shrysr** [bastibe/org-journal#151] opened 2019-03-26 17:45 UTC
Other than open journal file buffers, the org-agenda search does not include my journal files. I understand that `org-agenda-file-regexp` needs to be set and `(org-journal-update-auto-mode-alist)` should be called after this, but I am not able to get it working.

Setup:
- All my org files (and agenda files) are in ~/my_org
- org-journal directory is a subdirectory of the above: ~/my_org/journal/
- I already have one modification to org-agenda-file-regexp to include gpg files

```
(unless (string-match-p "\\.gpg" org-agenda-file-regexp)
  (setq org-agenda-file-regexp
        (replace-regexp-in-string "\\\\\\.org" "\\\\.org\\\\(\\\\.gpg\\\\)?"
                                  org-agenda-file-regexp)))
```

- I have also defined additional directories for the text search. This works fine for directories Other than the journal directory. I would have thought this to be sufficient.

```
(setq org-agenda-text-search-extra-files (apply 'append
						(mapcar
						 (lambda (directory)
						   (directory-files-recursively
						    directory org-agenda-file-regexp))
						 '("~/my_org/journal/"
                                                 "~/my_projects/" ))))
```

- After all the above is run, my org-journal setup is run.

```
(use-package org-journal
  :ensure t
  :defer t
  :custom
  (org-journal-dir "~/my_org/journal/")
  (org-journal-file-format "%Y%m%d")
  (org-journal-enable-agenda-integration t)
  (add-to-list 'auto-mode-alist '(".*/[0-9]*$" . org-mode))
```

I've tried adding the following:

```
(setq org-agenda-file-regexp ".*/[0-9]*$")
(org-journal-update-auto-mode-alist)
```

I would be glad for advice for the correct method to go about including journal files in the org-agenda search.

My thinking is that modifying the regex above for including .gpg files to also include ".*/[0-9]*$" should solve the problem.

**Comment by cslux** [comment] 2019-03-26 19:53
This should work for you
``` emacs-lisp
(use-package org-journal
  :ensure t
  :defer t
  :customs: 
  (org-journal-dir "~/my_org/journal/")
  (org-journal-enable-agenda-integration t)
  :config
  (setq org-agenda-file-regexp "\\`\\\([^.].*\\.org\\\|[0-9]\\\{8\\\}\\\(\\.gpg\\\)?\\\)\\'")
  (add-to-list 'org-agenda-files org-journal-dir))
```

**Comment by cslux** [comment] 2019-03-26 19:55
I have updated the readme as it is incorrect.

I'll close this issue as it works, but don't hesitate to post more question here.

**Closed by cslux** 2019-03-26 19:55 UTC

**Comment by shrysr** [comment] 2019-03-26 20:26
I just tried this. It does not work. Note: there is a typo in :custom 
I tried removing the earlier snippet to include .gpg files since it is now set in the org journal config. Now gpg files are also not showing up in the agenda, or even in agenda search.

**Comment by cslux** [comment] 2019-03-26 20:38
Works for me, not sure what else have changed!?

**Comment by cslux** [comment] 2019-03-26 20:40
With the default `org-journal-file-format-pattern` value this should actually work! I tested it my self.

**Comment by shrysr** [comment] 2019-03-26 20:42
I've just copied your snippet and removed the earlier snippet for gpg inclusion. No other changes :) Also tried reloading Emacs for good measure.

I have an extension to my question: 
I was going through the updated Readme and realised that I had not implemented complete agenda integration earlier as it was suggested that the inbuilt search is much faster. I do not want to slow down my agenda, and I have 189 journal files today. 

However, my understanding was that the journal files would be included as extra locations Only for text search via agenda, and not agenda generation itself (unless there is an active date tag) 

My goal is a unified search of my agenda files, journal files, and project files. Do you have any suggestions how I could do so?

**Comment by cslux** [comment] 2019-03-26 20:44
You could switch to weekly/monthly/yearly journal files if you like,  to make it faster.

**Comment by cslux** [comment] 2019-03-26 20:44
> However, my understanding was that the journal files would be included as extra locations Only for text search via agenda, and not agenda generation itself (unless there is an active date tag)

Nope! Like any other org file!

**Comment by shrysr** [comment] 2019-03-26 20:50
Hmm - by using org-agenda-file-regexp : I presume i am including everything in the agenda. 
However with org-agenda-text-search-extra-files , I believe these file lists are only used for search. why are my journal files not showing up using this >> Is it because I do not use an .org extension? My org based project files show up. 
```
(setq org-agenda-text-search-extra-files (apply 'append
						(mapcar
						 (lambda (directory)
						   (directory-files-recursively
						    directory org-agenda-file-regexp))
						 '("~/my_org/journal/"
                                                 "~/my_projects/" ))))
```

**Comment by cslux** [comment] 2019-03-26 20:52
> My goal is a unified search of my agenda files, journal files, and project files. Do you have any suggestions how I could do so?

Not at the moment, but I'll dig a bit around in the next time and will let you know whether I found something or not. 



> Hmm - by using org-agenda-file-regexp : I presume i am including everything in the agenda.
> However with org-agenda-text-search-extra-files , I believe these file lists are only used for search. why are my journal files not showing up using this >> Is it because I do not use an .org extension? My org based project files show up.



> Hmm - by using org-agenda-file-regexp : I presume i am including everything in the agenda.
> However with org-agenda-text-search-extra-files , I believe these file lists are only used for search. why are my journal files not showing up using this >> Is it because I do not use an .org extension? My org based project files show up.

Hmmm, I was not aware of the variable `org-agenda-text-search-extra-files`. Let me have quick look at it!

**Comment by cslux** [comment] 2019-03-26 20:57
Well, I tested it and it seems setting just `org-agenda-text-search-extra-files` is sufficient, to search in journal files... as well, fabulous.

**Comment by cslux** [comment] 2019-03-26 20:59
Content of my scratch buffer:

``` emacs-lisp
(setq org-agenda-text-search-extra-files (apply 'append
						(mapcar
						 (lambda (directory)
						   (directory-files-recursively
						    directory org-agenda-file-regexp))
						 '("~/emacs/org/journal"))))
("/home/cschwarzgruber/emacs/org/journal/20150101.gpg" "/home/cschwarzgruber/emacs/org/journal/20170101.gpg" "/home/cschwarzgruber/emacs/org/journal/20180101.gpg" "/home/cschwarzgruber/emacs/org/journal/20190101.gpg")
org-agenda-files
("/home/cschwarzgruber/emacs/org/agenda")
org-agenda-file-regexp
"\\`[^.].*\\.org\\'"
```

**Comment by shrysr** [comment] 2019-03-26 22:41
I finally got it working. :dancer:  I  had to set org-agenda-file-regexp to include the org journal format first. So I guess it means that setting org-agenda-file-regexp only dictates the format of the files and does not include them in the agenda itself.

Anyway - the results via agenda text search for multiple directories and only ~200 journal files is VERY slow, compared to using grep / rgrep / ag. The problem will only increase with more journal files. If the journal folder is within the same directory as org files - it is easy to use the above tools via Emacs. I'm trying to find a way to enable searching multiple directories.

Thank you for your quick help today !

**Comment by bastibe** [comment] 2019-03-27 08:21
That's why we included `org-journal-search`, which is super fast even for large numbers of files. The problem is that the agenda search opens every file in org-mode, and org-mode is pretty slow to load files. Using a weekly/monthly journal cuts down on the number of files, which makes it faster. But I prefer my daily journal.

**Comment by bastibe** [comment] 2019-03-28 13:10
My journal currently contains 1013 files, since 2016. `org-journal-search` is still incredibly snappy!

**Comment by shrysr** [comment] 2019-03-28 14:41
Thanks for sharing your workflow Bastian. I'm happy to find that my current workflow is quite similar. I was initially sceptical about the intermittent narrative approach and spreading information to daily files.  However, I've found it to be much more efficient and functional to maintain a detailed daily narrative, and review this regularly, rather than capture active date tagged notes in  large files, and then remember to archive them and etc.

I agree it is a good idea to  think 'wide' and incorporate as many keywords as possible, otherwise it becomes quite frustrating. I've found this becomes better only with practice and time, i.e when you actually search for something and find you did not record the one thing that you need now!
