### ISSUE TITLE
Encryption still not working when not using default config

### ISSUE THREAD

**Issue by dingmingxin** [bastibe/org-journal#49] opened 2015-07-17 11:01 UTC
Encryption still not working . Here is my configuration:

```
(setq org-journal-dir "~/wb/journal")
(setq org-journal-file-format "%Y%m%d.org") 
(setq org-journal-enable-encryption t)    
```

If I just added 

```
(setq org-journal-enable-encryption t) 
```

and do not change other settings , Encryption worked well. 
Version Info:

```
GNU Emacs 24.5.1 (x86_64-apple-darwin14.1.0)  
Org-mode version 8.2.10 (release_8.2.10 @ /opt/local/share/emacs/24.5/lisp/org/)
Mac OSX 10.10.3  with gnupg (gpg) command installed
```

**Comment by bastibe** [comment] 2015-07-24 11:05
What about it is not working?

**Comment by dingmingxin** [comment] 2015-07-28 02:33
It  won`t encrypt when I changed default configuration.

**Comment by bastibe** [comment] 2015-07-28 12:11
Does it add the `crypt` tag?

**Comment by dingmingxin** [comment] 2015-07-30 08:52
How to add `crypt` tag ? Adding to  Headers ?

**Comment by bastibe** [comment] 2015-09-07 10:18
Can you tell me the value of your `auto-mode-alist`? This seems to be related to another bug, where journal files are not opened in the right mode.

**Comment by bastibe** [comment] 2015-09-07 10:23
I uploaded a new version that should fix this bug. I'm still not entirely sure what causes this behavior.

**Comment by bastibe** [comment] 2015-09-21 06:47
Is the bug fixed now?

**Comment by bastibe** [comment] 2015-12-15 10:51
Can't reproduce and didn't get an more feedback, so I'm closing this. If you still have this issue, please reopen.

**Comment by ZzAntares** [comment] 2018-04-15 05:58
Hi @bastibe, I think I'm getting the exact problem in this issue, when adding `(setq org-journal-enable-encryption t)` then the journal opens up in Fundamental mode. If I remove that setting, it opens in the right mode.

**Comment by cslux** [comment] 2019-03-27 17:22
Closing this, as org-journal has been improved in many ways.

**Closed by cslux** 2019-03-27 17:22 UTC

**Comment by bastibe** [comment] 2019-03-28 13:07
Please reopen if you still experience this issue!
