### ISSUE TITLE
Properties and tags using all over diary entries

### ISSUE THREAD

**Issue by knevcher** [bastibe/org-journal#104] opened 2018-06-25 10:14 UTC
Hello

Is there any way to use cross-entries properties and tags? And search by it on whole diary entries?

**Comment by bastibe** [comment] 2018-06-26 06:51
Can you elaborate what you mean by that?

**Comment by cslux** [comment] 2019-03-27 17:19
Closing! As the initial reporter doesn't describe in more detail what the issue is.


@knevcher Please reopen it, if it is still an issue for you, and describe in more detail what is the problem.

**Closed by cslux** 2019-03-27 17:19 UTC
