### ISSUE TITLE
Search returns no results when filenames changed from default

### ISSUE THREAD

**Issue by jackbaty** [bastibe/org-journal#84] opened 2017-07-29 15:32 UTC
I have the following configured...

`(setq org-journal-file-format "%Y-%m-%d.org")`

Using org-journal-search-forever never returns any results. If I rename the files from, say, 2017-07-29.org to 20170729 the search works as expected. 

It's as if the search is not taking into account non-default filenames

**Comment by bastibe** [comment] 2017-08-09 07:35
I guess `org-journal-file-pattern` is not updated.

This happens automatically in some contexts, but apparently not in your case. I don't know why yet.

Can you run `(setq org-journal-file-pattern (org-journal-format-string->regex org-journal-file-format))`, and see if that fixes your problem?

**Comment by jackbaty** [comment] 2017-08-14 11:18
Sorry for the delay, but the machine I was running org-journal on has a dead hard drive so I won't be able to test this until it's repaired.

**Comment by factotvm** [comment] 2017-09-27 17:04
I'm also having this problem. I did run the code you suggested @bastibe, but my results are still empty. Here is the output from that expression: `"^\\(?1:[0-9]\\{4\\}\\)-\\(?2:[0-9][0-9]\\)-\\(?3:[0-9][0-9]\\).org\\'"`

I'm not an Emacs expert by any stretch, so I want to be clear on what I did:

1. Pasted your code after executing `M-:` and hit enter
2. Tried a search again

**Comment by bastibe** [comment] 2017-09-28 09:34
Interesting. The pattern looks fine to me, so the error is probably somewhere else.

It took some searching, but it turns out that I used `file-name-base` instead of `file-name-nondirectory` in a few places, which chopped off file extensions from the file name. And without the extension, the `org-journal-file-pattern` wouldn't match any more.

Should be fixed in 1.12.2. Can you confirm that the issue is fixed?

**Comment by tekacs** [comment] 2017-10-01 02:05
@bastibe I'm not the original commenter, but I had this issue previously and for me it's fixed in the latest release. Thanks! :tada:

**Comment by jackbaty** [comment] 2017-10-01 14:30
Sorry for not following up earlier. Yes, search works great now even with a custom file format. Thanks!

**Comment by jackbaty** [comment] 2017-10-01 15:49
I just noticed that the Spacemacs org layer now supports org-journal in the develop branch...

https://github.com/borgnix/spacemacs-journal/issues/5

However, when using org-journal via the Spacemacs org layer, the search fix in 1.12.2 no longer works as indicated earlier in this thread. Searches only include files named YYYYMMDD even though it looks to be using Version: 1.12.2.

Also there's a note in the [org layer documentation](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemacs/org#org-journal-support)

> Warning: setting org-journal-file-format to include a file extension like %Y-%m-%d.org breaks calender search functionality.

I assumed that was just out of date but perhaps not.

Maybe this is a spacemacs layer issue but thought I'd mention it here.

**Comment by bastibe** [comment] 2017-10-02 13:29
Thank you for the feedback!

I can't think of any reason why this functionality should not work in spacemacs. Maybe spacemacs' version is out of date? Anyway, if this issue persists, please open a new issue for it.

**Closed by bastibe** 2017-10-02 13:29 UTC

**Comment by tekacs** [comment] 2017-10-02 17:19
The above 'worked for me' was also on Spacemacs' develop branch.

Spacemacs doesn't pin versions, so it shouldn't be out of date.
